FROM google/dart:2.9.0-13.0.dev

RUN git clone https://github.com/l7ssha/nyxx.git

WORKDIR /nyxx
RUN git checkout rewrite_modular

WORKDIR ../app

ADD pubspec.* /app/
RUN pub get
ADD . /app
RUN pub get --offline

ENTRYPOINT ["/usr/bin/dart", "--enable-experiment=non-nullable", "--no-null-safety", "bin/beer_bot.dart"]