FROM zeruel92/dart-armv7:latest

#Install git
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

#Clone Nyxx with req. branch
RUN git clone -b rewrite_modular --single-branch https://github.com/l7ssha/nyxx.git

#Get req. Dart SDK
WORKDIR /opt/sdk
RUN wget https://storage.googleapis.com/dart-archive/channels/beta/release/2.9.0-14.1.beta/sdk/dartsdk-linux-arm-release.zip

RUN unzip -o dartsdk-linux-arm-release.zip
RUN rm dartsdk-linux-arm-release.zip

#Prep. Dart code
WORKDIR ../app

ADD pubspec.* /app/
RUN pub get
ADD . /app
RUN pub get --offline

#Run bot
CMD ["dart", "--enable-experiment=non-nullable", "--no-null-safety", "bin/beer_bot.dart"]