name: Agent_S
description: The Dart Discord bot for beer lovers in Sweden.
version: 1.0.0
homepage: https://github.com/oelburk/agentsbot
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cron: ^0.6.1
  hive: ^2.2.3
  intl: ^0.20.2
  nyxx: ^6.5.2
  nyxx_commands: ^6.0.3
  web_scraper:
    git: https://github.com/oelburk/web_scraper.git

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.4
  pedantic: ^1.11.1
