name: beer_bot
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>2.8.0 <3.0.0'

dependencies:
  nyxx: "^1.0.0"
  nyxx.commander: "^1.0.0"
  
dependency_overrides:
  nyxx:
    path: "../nyxx/nyxx"
  nyxx.commander:
    path: "../nyxx/nyxx.commander"
        
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
