name: Agent_S
description: The Dart Discord bot for beer lovers in Sweden.
version: 1.0.0
homepage: https://github.com/oelburk/agentsbot

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cron: ^0.5.1
  hive: ^2.2.3
  intl: ^0.18.1
  nyxx: ^5.1.0
  nyxx_commands: ^5.0.2
  nyxx_interactions: ^4.6.0
  web_scraper: ^0.1.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
  pedantic: ^1.11.1
