name: Agent_S
description: The Dart Discord bot for beer lovers in Sweden.
version: 1.0.0
homepage: https://github.com/oelburk/agentsbot

environment:
  sdk: '>2.8.0 <3.0.0'

dependencies: 
  intl: ^0.17.0
  nyxx: ^3.2.3
  nyxx_commander: ^3.0.0
  nyxx_interactions: ^3.3.0
 

dev_dependencies:
  pedantic: ^1.9.0
