name: Agent_S
description: The Dart Discord bot for beer lovers in Sweden.
version: 1.0.0
homepage: https://github.com/oelburk/agentsbot

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  hive: ^2.2.3
  intl: ^0.17.0
  nyxx: ^3.2.3
  nyxx_commander: ^3.0.0
  nyxx_interactions: ^3.3.0
  web_scraper: ^0.1.4
 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  pedantic: ^1.9.0
